export const START_FETCHING_PHONES = "START_FETCHING_PHONES";
export const FETCH_PHONES_SUCCESS = "FETCH_PHONES_SUCCESS";
export const FETCH_PHONES_FAIL = "FETCH_PHONES_FAIL";

export const START_FETCHING_PHONE = "START_FETCHING_PHONE";
export const FETCH_PHONE_SUCCESS = "FETCH_PHONE_SUCCESS";
export const FETCH_PHONE_FAIL = "FETCH_PHONE_FAIL";
